version: 0.2

phases:
  build:
    commands:
      - aws deploy push --application-name h4b-app --s3-location s3://codebuild-ap-northeast-1-850470019323-output-bucket /artifact.zip --source src
artifacts:
  files:
    - '**/*'
  base-directory: src